# don't specify: language: perl
os:
  - osx
env: BBBIKE_TEST_SKIP_MODPERL=1 BBBIKE_TEST_SKIP_MAPSERVER=1 BBBIKE_TEST_GUI=1
sudo: true

branches:
  except:
    - /appveyor/

before_install:
# Required system dependencies
# * cpanminus           for installing CPAN modules
# * mysql-connector-c   for DBD::mysql
# * gd                  for GD
# * cairo               for Cairo
# * pango               for Pango
# * glib                for Glib
# * libpng jpeg         for Imager (giflib is already installed, it seems)
# * bsdmake             e.g. for building data-test
  - brew install cpanminus mysql-connector-c gd cairo pango glib libpng jpeg bsdmake
  - git clone --depth=1 https://github.com/eserte/bbbike.git
  - cd bbbike

install:
# XXX Tk::ExecuteCommand does not specify Tk as a prereq,
# so make sure to install Tk early. See
# https://rt.cpan.org/Ticket/Display.html?id=102434
  - cpanm --sudo --quiet --notest Tk
# re ARCHFLAGS see https://github.com/Homebrew/homebrew-core/issues/5404
  - ARCHFLAGS="-arch x86_64" cpanm --sudo --quiet --notest Pango Imager
  - cpanm --sudo --quiet --installdeps --notest . || true

script:
  - make ext
  - cd t && make test-no-cgi
