language: perl
perl:
 - "5.18"
 - "5.8"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb $WINDOW_MANAGER
 - env DISPLAY= Xvfb :123 2>/dev/null &
 - (sleep 10; env DISPLAY=:123 $WINDOW_MANAGER) &
 - sleep 11
env:
 - DISPLAY=:123 WINDOW_MANAGER=fvwm
 - DISPLAY=:123 WINDOW_MANAGER=metacity
