## test-fakesendmail testing
#language: perl
#perl:
# - "5.10"
#before_install:
# - cpanm --quiet --notest MIME::Lite
# - cpanm git://github.com/eserte/test-fakesendmail.git@master
#before_script:
# - sudo -E `which perl` -MTest::FakeSendmail -e 'Test::FakeSendmail->install(maildirectory => "/tmp/tfsm")'

# modperl testing
language: perl
perl:
 - "5.20-shrplib"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install apache2-mpm-prefork apache2-prefork-dev
 - env APACHE_TEST_HTTPD=/usr/sbin/apache2 APACHE_TEST_TRACE_LEVEL=debug cpanm --verbose mod_perl2 --configure-args="MP_APXS=/usr/bin/apxs2 MP_AP_DESTDIR=/home/travis/perl5/perlbrew/perls/5.20-shrplib/" || (echo "Contents of Apache2/BuildConfig.pm:"; cat /home/travis/.cpanm/work/*/mod_perl-2*/lib/Apache2/BuildConfig.pm; false)
 - echo "LoadModule perl_module /home/travis/perl5/perlbrew/perls/5.20-shrplib/usr/lib/apache2/modules/mod_perl.so" > /etc/apache2/mods-enabled/perl.load
 - sudo service apache start

#language: perl
#matrix:
#  include:
#    - perl: 5.18
#      env: WITH_XML_LIBXML_READER=1
#before_install:
#  - '[ "$WITH_XML_LIBXML_READER" = 1 ] && cpanm XML::LibXML::Reader || true'
