# don't specify: language: perl
os:
  - osx
sudo: true

branches:
  except:
    - /appveyor/

before_install:
# Required system dependencies
# * cpanminus           for installing CPAN modules
  - brew install cpanminus
# Special deps
  - brew install glib

install:
  - cpanm --sudo --verbose Glib

script:
  - true
