branches:
  except:
    - /appveyor/

#os:
#  - linux
#  - osx

#before_install:
#  - mkdir -p $HOME/.cpan/CPAN
#  - ln -s $(pwd)/.cpan/CPAN/MyConfig.pm $HOME/.cpan/CPAN/MyConfig.pm
#  - git clone https://github.com/eserte/srezic-cpan-distroprefs $HOME/.cpan/prefs
#  - mkdir -p $HOME/src
#  - git clone https://github.com/eserte/cpan-plugin-sysdeps $HOME/src/cpan-plugin-sysdeps
#  - (cd $HOME/src/cpan-plugin-sysdeps && perl Makefile.PL && make all test && sudo make install)
#  - cpan CPAN YAML::Syck
#before_install:
#  - git clone https://github.com/eserte/travis-helper-cpan-pm.git
#  - ./travis-helper-cpan-pm/travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps
#  - which cpan
#install:
##  - cpan GD File::Rdiff
#  - cpan File::Rdiff

## test-fakesendmail testing
#language: perl
#perl:
# - "5.10"
#before_install:
# - cpanm --quiet --notest MIME::Lite
# - cpanm git://github.com/eserte/test-fakesendmail.git@master
#before_script:
# - sudo -E `which perl` -MTest::FakeSendmail -e 'Test::FakeSendmail->install(maildirectory => "/tmp/tfsm")'

## modperl testing
#language: perl
#perl:
# - "5.20-shrplib"
#before_install:
# - echo "deb http://de.archive.ubuntu.com/ubuntu/ precise multiverse" | sudo tee -a /etc/apt/sources.list
# - sudo apt-get update
# - sudo apt-get install tre-agrep
# - sudo apt-cache search agrep
# - sudo apt-cache policy agrep
# - sudo apt-cache show agrep
# - sudo apt-get install apache2-mpm-prefork apache2-prefork-dev
# - cpanm --quiet --notest mod_perl2 --configure-args="MP_APXS=/usr/bin/apxs2 MP_AP_DESTDIR=/home/travis/perl5/perlbrew/perls/5.20-shrplib/" || (echo "Contents of Apache2/BuildConfig.pm:"; cat /home/travis/.cpanm/work/*/mod_perl-2*/lib/Apache2/BuildConfig.pm; false)
# - sudo sh -c 'echo "LoadModule perl_module /home/travis/perl5/perlbrew/perls/5.20-shrplib/usr/lib/apache2/modules/mod_perl.so" > /etc/apache2/mods-enabled/perl.load'
# - sudo service apache2 start
#  - cpanm --notest DBD::XBase~"!=1.00, !=1.01, !=1.02, !=1.03, !=1.04, !=1.05"
#  - cpanm --notest DBD::XBase~"==0.234"

#language: perl
#matrix:
#  include:
#    - perl: 5.18
#      env: WITH_XML_LIBXML_READER=1
#before_install:
#  - '[ "$WITH_XML_LIBXML_READER" = 1 ] && cpanm XML::LibXML::Reader || true'

#sudo: false
sudo: true

#addons:
#  apt:
#    packages:
## for DB_File
#      - libdb-dev
## for XML::LibXML::SAX
#      - libxml2-dev

language: perl
matrix:
  include:
#    - perl: "5.24"
#    - perl: "5.24"
#      dist: trusty
#    - perl: "5.18"
#      os: osx
#    - perl: "5.14"
#      sudo: false
#    - perl: "5.14"
#    - perl: "5.20"
#    - perl: "5.18"
#    - perl: "5.14"
#    - perl: "5.10"
    - perl: "5.20-shrplib"
#    - perl: "5.8"

#before_install:
# # XXX DBD-mysql-4.034 fails to specify DBI::DBD as a prereq
# # https://rt.cpan.org/Ticket/Display.html?id=115167
# - cpanm --quiet --notest DBI::DBD
# - cpanm --verbose DBD::mysql

install:
 - cpanm --quiet --notest App::cpm
 - perl Makefile.PL
 - mymeta-cpanfile > cpanfile~ && mv cpanfile~ cpanfile
# - cpm install -g -v DBD::XBase~"==0.234" File::Path DB_File~"!=1.833"
 - cpm install -g -v

#install:
# # cpanm is not available on MacOSX, so don't do anything here...
# # see https://github.com/travis-ci/travis-ci/issues/2314
# - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cpanm --quiet --installdeps --notest .; fi

script:
# - perl Makefile.PL && make test HARNESS_OPTIONS=j4
 - make test HARNESS_OPTIONS=j4
