## test-fakesendmail testing
#language: perl
#perl:
# - "5.10"
#before_install:
# - cpanm --quiet --notest MIME::Lite
# - cpanm git://github.com/eserte/test-fakesendmail.git@master
#before_script:
# - sudo -E `which perl` -MTest::FakeSendmail -e 'Test::FakeSendmail->install(maildirectory => "/tmp/tfsm")'

## modperl testing
#language: perl
#perl:
# - "5.20-shrplib"
before_install:
 - sudo apt-get update
# - sudo apt-get install agrep
 - sudo apt-cache search agrep
 - sudo apt-cache policy agrep
 - sudo apt-cache show agrep
# - sudo apt-get install apache2-mpm-prefork apache2-prefork-dev
# - cpanm --quiet --notest mod_perl2 --configure-args="MP_APXS=/usr/bin/apxs2 MP_AP_DESTDIR=/home/travis/perl5/perlbrew/perls/5.20-shrplib/" || (echo "Contents of Apache2/BuildConfig.pm:"; cat /home/travis/.cpanm/work/*/mod_perl-2*/lib/Apache2/BuildConfig.pm; false)
# - sudo sh -c 'echo "LoadModule perl_module /home/travis/perl5/perlbrew/perls/5.20-shrplib/usr/lib/apache2/modules/mod_perl.so" > /etc/apache2/mods-enabled/perl.load'
# - sudo service apache2 start

#language: perl
#matrix:
#  include:
#    - perl: 5.18
#      env: WITH_XML_LIBXML_READER=1
#before_install:
#  - '[ "$WITH_XML_LIBXML_READER" = 1 ] && cpanm XML::LibXML::Reader || true'

language: perl
matrix:
  include:
    - perl: 5.18
sudo: true
addons:
  apt:
    packages:
# for DB_File
      - libdb-dev
# for XML::LibXML::SAX
      - libxml2-dev
