os: linux
arch:
  - arm64
#  - ppc64le
#  - s390x

#os:
#  - linux
#  - osx

#before_install:
#  - mkdir -p $HOME/.cpan/CPAN
#  - ln -s $(pwd)/.cpan/CPAN/MyConfig.pm $HOME/.cpan/CPAN/MyConfig.pm
#  - git clone https://github.com/eserte/srezic-cpan-distroprefs $HOME/.cpan/prefs
#  - mkdir -p $HOME/src
#  - git clone https://github.com/eserte/cpan-plugin-sysdeps $HOME/src/cpan-plugin-sysdeps
#  - (cd $HOME/src/cpan-plugin-sysdeps && perl Makefile.PL && make all test && sudo make install)
#  - cpan CPAN YAML::Syck

#before_install:
#  - git clone https://github.com/eserte/travis-helper-cpan-pm.git
#  - ./travis-helper-cpan-pm/travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps --no-sudo
#  - which cpan
##install:
##  - cpan DB_File
###  - cpan GD File::Rdiff
##  - cpan File::Rdiff

## test-fakesendmail testing
#language: perl
#perl:
# - "5.10"
#before_install:
# - cpanm --quiet --notest MIME::Lite
# - cpanm git://github.com/eserte/test-fakesendmail.git@master
#before_script:
# - sudo -E `which perl` -MTest::FakeSendmail -e 'Test::FakeSendmail->install(maildirectory => "/tmp/tfsm")'

## modperl testing
#language: perl
#perl:
# - "5.20-shrplib"
#before_install:
# - echo "deb http://de.archive.ubuntu.com/ubuntu/ precise multiverse" | sudo tee -a /etc/apt/sources.list
# - sudo apt-get update
# - sudo apt-get install tre-agrep
# - sudo apt-cache search agrep
# - sudo apt-cache policy agrep
# - sudo apt-cache show agrep
# - sudo apt-get install apache2-mpm-prefork apache2-prefork-dev
# - cpanm --quiet --notest mod_perl2 --configure-args="MP_APXS=/usr/bin/apxs2 MP_AP_DESTDIR=/home/travis/perl5/perlbrew/perls/5.20-shrplib/" || (echo "Contents of Apache2/BuildConfig.pm:"; cat /home/travis/.cpanm/work/*/mod_perl-2*/lib/Apache2/BuildConfig.pm; false)
# - sudo sh -c 'echo "LoadModule perl_module /home/travis/perl5/perlbrew/perls/5.20-shrplib/usr/lib/apache2/modules/mod_perl.so" > /etc/apache2/mods-enabled/perl.load'
# - sudo service apache2 start
#  - cpanm --notest DBD::XBase~"!=1.00, !=1.01, !=1.02, !=1.03, !=1.04, !=1.05"
#  - cpanm --notest DBD::XBase~"==0.234"

#language: perl
#matrix:
#  include:
#    - perl: 5.18
#      env: WITH_XML_LIBXML_READER=1
#before_install:
#  - '[ "$WITH_XML_LIBXML_READER" = 1 ] && cpanm XML::LibXML::Reader || true'

#sudo: false
#sudo: true

#addons:
#  apt:
#    packages:
#     - strace
#      - libx11-dev
#      - libxcursor-dev
#      - libxpm-dev
#      - libgif-dev
#      - libpng12-dev
#      - libjpeg-dev
#      - pkg-config
#      - traceroute
#      - libwww-perl
#      - apt-file
#      - pdftk
#      - poppler-utils
#      - libgd-dev
##      - libx11-dev
##      - libfreetype6-dev
##      - libxft-dev
##      - apache2-mpm-prefork
##      - libapache2-mod-perl2
#### for DB_File
###      - libdb-dev
#### for XML::LibXML::SAX
###      - libxml2-dev

before_install:
##  - date
##  - which sudo
#  - (cd /etc/apt/sources.list.d && sudo rm -f mongodb.list google-chrome.list cassandra.list github_git-lfs.list couchdb.list pgdg.list)
#  - sudo grep . /etc/apt/sources.list.d/*.list
#  - sudo rm -f /etc/apt/sources.list.d/*.list
#  - sudo ls -al /etc/apt/sources.list.d
#  - sudo apt-get update
####  - sudo -E apt-get install freebsd-buildutils libproj-dev proj-bin libdb-dev agrep tre-agrep libgd2-xpm-dev ttf-bitstream-vera ttf-dejavu gpsbabel xvfb fvwm rhino imagemagick libpango1.0-dev libxml2-utils libzbar-dev pdftk poppler-utils tzdata

language: perl
matrix:
  include:
    - language: minimal
      dist: focal

#    - perl: '5.32'
#      dist: focal

#    - perl: '5.8'
#      dist: precise
#    - perl: '5.10'
#      dist: precise
#    - perl: '5.12'
#      dist: precise
#    - perl: '5.14'
#      dist: precise
#    - perl: '5.16'
#      dist: precise
#    - perl: '5.18'
#      dist: precise
#    - perl: '5.20'
#      dist: precise
#    - perl: '5.22'
#      dist: precise
#    - perl: '5.24'
#      dist: precise

#    - perl: '5.8'
#      dist: trusty
#    - perl: '5.10'
#      dist: trusty
#    - perl: '5.12'
#      dist: trusty
#    - perl: '5.14'
#      dist: trusty
#    - perl: '5.16'
#      dist: trusty
#    - perl: '5.18'
#      dist: trusty
#    - perl: '5.20'
#      dist: trusty
#    - perl: '5.22'
#      dist: trusty
#    - perl: '5.24'
#      dist: trusty

#    - perl: '5.8'
#      dist: xenial
#    - perl: '5.10'
#      dist: xenial
#    - perl: '5.12'
#      dist: xenial
#    - perl: '5.14'
#      dist: xenial
#    - perl: '5.16'
#      dist: xenial
#    - perl: '5.18'
#      dist: xenial
#    - perl: '5.20'
#      dist: xenial
#    - perl: '5.22'
#      dist: xenial
#    - perl: '5.24'
#      dist: xenial

#     - perl: '5.30'
#       dist: focal
#     - perl: '5.28'
#       dist: focal
#     - perl: '5.26'
#       dist: focal
#     - perl: '5.24'
#       dist: focal
#     - perl: '5.22'
#       dist: focal
#     - perl: '5.20'
#       dist: focal
#     - perl: '5.18'
#       dist: focal
#     - perl: '5.16'
#       dist: focal
#     - perl: '5.14'
#       dist: focal
#     - perl: '5.12'
#       dist: focal


#     - perl: '5.34'
#       dist: bionic
#     - perl: '5.32'
#       dist: bionic
#     - perl: '5.30'
#       dist: bionic
#     - perl: '5.28'
#       dist: bionic
#     - perl: '5.26'
#       dist: bionic
#     - perl: '5.24'
#       dist: bionic
#     - perl: '5.22'
#       dist: bionic
#     - perl: '5.20'
#       dist: bionic
#     - perl: '5.18'
#       dist: bionic
#     - perl: '5.16'
#       dist: bionic
#     - perl: '5.14'
#       dist: bionic
#     - perl: '5.12'
#       dist: bionic
#     - perl: '5.10'
#       dist: bionic

#    - dist: xenial
#      perl: 5.24

#    - perl: '5.32'
#      dist: bionic
#    - perl: '5.30'
#      dist: xenial
#    - perl: blead
#    - perl: '5.28'
#    - perl: '5.26'
#    - perl: '5.28'
#    - perl: '5.30'
#    - perl: "5.14"
#      dist: precise
#    - perl: "5.24"
#    - perl: "5.18"
#    - perl: "5.10"
#      dist: precise
#      sudo: true
#    - perl: "5.8"
#      dist: trusty
#    - os: osx
#      osx_image: xcode12.2
#      language: ruby
#    - perl: "5.24"
#      dist: trusty
##    - perl: "5.24"
##      sudo: true
##      os: osx
###    - perl: "5.14"
###      sudo: false
#    - perl: "5.20"
#      dist: precise
#    - perl: "5.12"
#      dist: precise
##    - perl: "5.18"
##    - perl: "5.14"
#    - perl: "5.20-shrplib"
##    - perl: "5.6.2"
#    - perl: "5.20"
#      dist: trusty

#before_install:
#  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
#  - source ~/travis-perl-helpers/init
#  - build-perl
#  - perl -V
#  - build-dist
#  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command

#install:
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew uninstall --cask --force java || true; fi
#  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cpanminus; fi
#  - sudo cpanm --quiet --notest Kwalify

#install:
#  - cpan-install --deps       # installs prereqs, including recommends

#install:
#  - cpanm DBI http://backpan.cpantesters.org/authors/id/J/JA/JANPAZ/DBD-XBase-0.234.tar.gz
# || cat /home/travis/.cpanm/work/*/build.log
#before_install:
# # XXX DBD-mysql-4.034 fails to specify DBI::DBD as a prereq
# # https://rt.cpan.org/Ticket/Display.html?id=115167
# - cpanm --quiet --notest DBI::DBD
# - cpanm --verbose DBD::mysql

#install:
# - cpanm --quiet --notest 'App::cpm~>=0.292'
# - perl Makefile.PL
# - mymeta-cpanfile > cpanfile~ && mv cpanfile~ cpanfile
### - cpm install -g -v DBD::XBase~"==0.234" File::Path DB_File~"!=1.833"
### XXX cpm seems to fail if this directory does not exist -> https://github.com/skaji/cpm/issues/60
### - mkdir ~/.perl-cpm
# - if ! cpm install -g -v; then cat ~/.perl-cpm/build.log; false; fi

#install:
# # cpanm is not available on MacOSX, so don't do anything here...
# # see https://github.com/travis-ci/travis-ci/issues/2314
# - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cpanm --quiet --installdeps --notest .; fi

#install:
#  - git clone http://github.com/eserte/doit
#  - perl -Idoit/lib -MDoit -MData::Dumper -e 'my $d = Doit->init; $d->add_component("brew"); $d->brew_install_packages("perl"); warn Dumper($d->brew_missing_packages("perl"))'

#install:
## Should fail!
# - cpan Devel::Fail::MakeTest

#install:
# - cpanm --notest http://backpan.perl.org/authors/id/J/JA/JANPAZ/DBD-XBase-0.234.tar.gz 

#install:
# - cpanm https://github.com/dk/Prima.git@eeceef6ba4faf2a8842d4215aba2a8cf1c5abeef

#script:
#  - perl "-MNet::SSLeay 999999" -e1 || true
#  - perl -MLWP -e 'warn LWP::UserAgent->new->head("https://download.bbbike.org")->dump'

#script:
#  - sudo apt update -y
#  - sudo apt install -y wget libssl1.0.0
#  - ldd $(which wget) | egrep '(ssl|tls)'
#  - apt-cache policy ca-certificates
#  - apt-cache policy libssl1.0.0
#  - cd /tmp && wget https://download.bbbike.org

#script:
#  - perl -MKwalify -E 'say $Kwalify::VERSION'

#script:
# - perl Makefile.PL && make test HARNESS_OPTIONS=j4
# - make test HARNESS_OPTIONS=j4
# - apt-file update
# - grep --with-filename . /etc/apt/sources.list /etc/apt/sources.list.d/*
# - apt-file search /Moose.pm
# - git clone https://github.com/eserte/srezic-misc.git
# - ./srezic-misc/scripts/pm-to-deb -v Moose
# - ./srezic-misc/scripts/pm-to-deb -v --ignore-installed Moose

#script:
# - ls -ald ~
# - ls -al /etc/apache2/mods-enabled/
# - ls -al /etc/apache2/mods-available/
# - strace -o /tmp/strace.log perl -e1
# - cat /tmp/strace.log

# specific BBBike-Testing
#script:
# - strace -f -s2048 -tt -T -o/tmp/strace.log cpanm --verbose DBD::XBase~"==0.234" || true
# - grep "GET /" /tmp/strace.log
# - perl -V
# - cpanm --quiet --notest 'PDF::Create~==1.43' 'Image::Info' 'GD'
# - cpanm --quiet --notest XML::LibXML LWP::UserAgent
# - git clone --depth=1 https://github.com/eserte/bbbike.git
# - cd bbbike
## travis does not like this -> translated to {:"prove -v t/bbbikedraw.t :"=>"-only PDF"}
# - prove -v t/bbbikedraw.t :: -only PDF
# - strace -f -e recvfrom,sendto,write,writev,read,connect,accept -s128 -tt -T perl t/bbbike-org-download.t
# - perl t/bbbike-org-download.t
# - perl -e 'sleep(rand(30))'
# - perl -e 'exit(rand(2) < 1 ? 1 : 0)'

script:
 - sudo apt-get update && sudo apt-get install libipc-run-perl
 - git clone --depth=1 https://github.com/eserte/bbbike.git
 - cd bbbike
 - /usr/bin/perl ./miscsrc/docker-bbbike ci --dist ubuntu --distver focal --src local

#after_script:
# - true

## Just download something
#script:
# - lwp-request -t 10 -mHEAD -eS http://download.bbbike.org
# - lwp-request -t 10 -mHEAD -eS https://download.bbbike.org
# - lwp-request -t 10 -mHEAD -eS http://extract.bbbike.org
# - lwp-request -t 10 -mHEAD -eS https://extract.bbbike.org
# - curl --connect-timeout 10 --head http://download.bbbike.org
# - curl --connect-timeout 10 --head https://download.bbbike.org
# - curl --connect-timeout 10 --head http://extract.bbbike.org
# - curl --connect-timeout 10 --head https://extract.bbbike.org
# - traceroute download.bbbike.org
# - ping -c 1 download.bbbike.org

#before_install:
# - . travis-functions.sh
# - init_travis
#
#install:
# - cpanm --quiet --notest App::cpanminus
# - wrapper install_perl_dependencies

#before_script:
#  - grep -r . /etc/apt/apt.conf.d/
#  - grep    . /etc/apt/apt-file.conf
#  - sudo rm -f /etc/apt/apt.conf.d/99-travis-apt-proxy
#  - sudo apt-file update

#script:
#  - perl -e 'print $], "\n"'

#before_script:
#  - perlbrew off

#script:
#  - perlbrew off
#  - sudo add-apt-repository ppa:eserte/bbbike
#  - sudo apt-get install -y libarray-heap-perl
#  - perl -MArray::Heap -E 'say $Array::Heap::VERSION'

branches:
  except:
    - /appveyor/
    - /github-actions/
    - /doozer/
