#language: perl
#perl:
# - "5.18"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq perl-tk xvfb xfonts-cyrillic defoma
 - env DISPLAY= Xvfb :123 &
env:
 - DISPLAY=:123
script:
 - make
