language: perl
perl:
 - "5.18"
 - "5.16"
 - "5.14"
 - "5.12"
 - "5.10"
 - "5.8"
before_install:
 - cpanm PDF::Create~"!=1.07"
##env:
## - DISPLAY=:123 WINDOW_MANAGER=fvwm
## - DISPLAY=:123 WINDOW_MANAGER=metacity
#before_install:
# - sudo apt-get update -qq
# - sudo apt-get install -qq xvfb $WINDOW_MANAGER
# - sudo apt-get remove -qq libjpeg8-dev zlib1g-dev libpng12-dev
# - env DISPLAY= Xvfb :123 2>/dev/null &
# - (sleep 10; env DISPLAY=:123 $WINDOW_MANAGER) &
# - sleep 11
#matrix:
# include:
##  - perl: "5.18"
##    env: DISPLAY=:123 WINDOW_MANAGER=metacity
##  - perl: "5.14"
##    env: DISPLAY=:123 WINDOW_MANAGER=sawfish
#  - perl: "5.10"
#    env: DISPLAY=:123 WINDOW_MANAGER=fvwm
#  - perl: "5.8"
#    env: DISPLAY=:123 WINDOW_MANAGER=twm
