# don't specify: language: perl
os:
  - osx
sudo: true

branches:
  except:
    - /appveyor/

before_install:
# Required system dependencies
# * cpanminus           for installing CPAN modules
  - brew install cpanminus
# Special deps
  - brew install libpng jpeg giflib || true

install:
  - cpanm --sudo --verbose Imager

script:
  - |
    perl -MImager -e 'warn q{read types: } . join(q{, }, Imager->read_types), qq{\n}; warn q{write types: } . join(q{, }, Imager->write_types), qq{\n}'
