branches:
  except:
    - /travis/
skip_tags: true
shallow_clone: true

cache:
  - C:\strawberry
  - C:\Perl

install:
  - if not exist "C:\strawberry" cinst strawberryperl
##  - ps: Start-FileDownload http://strawberryperl.com/download/5.22.1.2/strawberry-perl-5.22.1.2-64bit.msi
##  - msiexec /i "C:\projects\sources\strawberry-perl-5.22.1.2-64bit.msi" /qn INSTALLDIR="C:\projects\perl"
  - set PATH=C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
#  - if not exist "C:\Perl" cinst activeperl
#  - set PATH=C:\Perl\bin;%PATH%
#  - ppm install App-cpanminus MinGW
#  - if not exist "C:\strawberry\cpan\prefs\.git" git clone git://github.com/eserte/srezic-cpan-distroprefs C:\strawberry\cpan\prefs
#  - cd C:\strawberry\cpan\prefs
#  - git pull
#  - cpan DB_File::Lock
#  - cpanm Tk
#  - cpanm --verbose Tk::Pod
#  - set USE_MAKE=nmake
  - set USE_MAKE=dmake
  - cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - cpanm --installdeps .

build_script:
  - perl Makefile.PL
#  - perl -MDB_File::Lock -e "warn $DB_File::Lock::VERSION"
#  - "%USE_MAKE% dmake-test SOMETHING=nesto PERL=perl"
  - "%USE_MAKE% test"

on_failure:
  - type C:\ProgramData\chocolatey\logs\chocolatey.log
