=head1 sandbox

=for html
<a href="https://travis-ci.org/eserte/sandbox"><img src="https://travis-ci.org/eserte/sandbox.svg" alt="Travis CI"></a>
<a href="https://ci.appveyor.com/project/eserte/sandbox"><img src="https://ci.appveyor.com/api/projects/status/github/eserte/sandbox?svg=true" alt="Appveyor"></a>

A project just for testing ci systems like travis-ci or appveyor

=cut
