name: Check for mydebs connection problems

on:
  workflow_dispatch:
  schedule:
    - cron: '20 9 * * *'

jobs:
  mydebs-check:
    if: true
    runs-on: ubuntu-latest
    container: debian:jessie
    steps:
      - name: install prereqs
        run: |
          set -ex
          apt-get update -qq && apt-get install -y curl
      - name: network check
        run: |
          echo "My IP address: $(curl -s ipinfo.io/ip)"; true
          curl -v --connect-timeout 5 http://bbbike.de/robots.txt > /dev/null
