name: Check for mydebs connection problems

on:
  workflow_dispatch:

jobs:
  mydebs-check:
    if: true
    runs-on: ubuntu-latest
    container: debian:jessie
    steps:
      - run: |
          echo "My IP address: $(curl -s ipinfo.io/ip)"; true
          curl -v --connect-timeout 5 http://bbbike.de/robots.txt > /dev/null
