name: Check for mydebs connection problems

on:
  workflow_dispatch:
  schedule:
    - cron: '37 9,21 * * *'

jobs:
  mydebs-check:
    if: true
    runs-on: ubuntu-latest
#    container: debian:jessie
    steps:
      - name: install prereqs
        run: |
          set -ex
          which curl >/dev/null || { apt-get update -qq && apt-get install -y curl; }
      - name: network check
        shell: bash
        run: |
          set -ex
          echo "My IP address: $(curl -s ipinfo.io/ip)"; true
          { set -o pipefail; curl -s -I http://bbbike.de/robots.txt | head -1; } || { echo "::warning::network check on port 80 failed"; }
          { set -o pipefail; curl -s -I http://mydebs.bbbike.de:8000/dists/jessie/InRelease | head -1; true; } || { echo "::warning::network check on port 8000 failed"; }
          { set -o pipefail; curl -s -I https://download.bbbike.org/robots.txt | head -1; } || { echo "::warning::network check for download.bbbike.org failed"; }
