name: Test anything with perl images

on:
  workflow_dispatch:

jobs:
  test-perl-anything:
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - image: perl:5.8.9-threaded-stretch
          - image: perl:5.10.1-buster
          - image: perl:5.12.5-stretch
          - image: perl:5.14.4-stretch
          - image: perl:5.16.3-buster
          - image: perl:5.18.4-buster
          - image: perl:5.22.4-stretch
          - image: perl:5.36.0-slim-bullseye
          - image: perl:5.38.0-slim-bookworm
    steps:
      - uses: actions/checkout@v4
      - run: |
          cpanm Digest@1.17
          perl  -MDigest::file -e 'warn "Digest::file $Digest::file::VERSION"; warn "Digest $Digest::VERSION"; eval { Digest::file::digest_file_hex($^X, "This_Dies_Doest_Not_Exist_0.12345") }; warn $@'
