name: Test anything with perl images

on:
  workflow_dispatch:
    inputs:
      preinstall:
        default: 'Digest@1.17'

jobs:
  test-perl-anything:
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: perl:5.8.9-threaded-stretch
          - image: perl:5.10.1-buster
          - image: perl:5.12.5-stretch
          - image: perl:5.14.4-stretch
          - image: perl:5.16.3-buster
          - image: perl:5.18.4-buster
          - image: perl:5.22.4-stretch
          - image: perl:5.36.0-slim-bullseye
          - image: perl:5.38.0-slim-bookworm
    steps:
      - uses: actions/checkout@v3
      - run: |
          cpanm ${{ inputs.preinstall }}
          perl  -MDigest::file -e 'eval { Digest::file::digest_file_hex($^X, "This_Dies_Doest_Not_Exist_0.12345") }; print "::notice::Digest::file $Digest::file::VERSION - Digest $Digest::VERSION - error message is: $@\n"'
          which git || (apt-get -qqy update && apt-get -qqy install git)
          git clone -b XXX-github-actions https://github.com/eserte/Doit
          cd Doit && perl Build.PL && ./Build test
