name: Test on FreeBSD

on:
  workflow_dispatch:

jobs:
  test:
    name: Test on FreeBSD
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v4
      with:
        clean: false
        show-progress: false
    - uses: cross-platform-actions/action@v0.21.1
      with:
        operating_system: freebsd
        version: '13.2'
        shell: sh
        run: |
          echo "Hello, world! (using shell $SHELL)"
          which killall
          which pkill
