name: Test install-doit-from-github action

on:
  workflow_dispatch:

jobs:
  test-install-doit-from-github:
    name: Test Doit.pm installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: eserte/sandbox/.github/actions/install-doit-from-github@master
      - run: |
          perl -MDoit -MDoit::Log -E 'info "hello world"'
