name: CI

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: |
        perl Makefile.PL
        make all test
      if: "!startsWith(matrix.os,'windows-')"
    - name: Build and test on Windows
      run: |
        c:\strawberry\bin\perl Makefile.PL
        gmake all test
      if: "startsWith(matrix.os, 'windows-')"
