name: Trigger

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test options'
        required: true
        default: two
        type: choice
        options:
          - one
          - two
          - three

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: just testing
        run: |
          echo "Hello world"
          echo "You selected ${{ github.event.inputs.test }}"
          date
