name: Trigger

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test options'
        required: true
        default: two
        type: choice
        options:
          - one
          - two
          - three

concurrency: trigger

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "info environment=${{github.event.inputs.test}}"
        run: "echo environment=${{github.event.inputs.test}}"
