name: Trigger

on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Test options'
        required: true
        default: two
        type: choice
        options:
          - one
          - two
          - three

concurrency: trigger

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "info environment=${{github.event.inputs.test}}"
        run: "echo environment=${{github.event.inputs.test}}"
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dummy artifact file
        run: "touch /tmp/dummy-artifact"
      - uses: actions/upload-artifact@v3
        name: Create artifact for informational purposes
        with:
          name: "info test=${{github.event.inputs.test}}"
          path: /tmp/dummy-artifact
