name: Test anything on windows

on:
  workflow_dispatch:

jobs:
  test-windows-anything:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          prove -v t\inc_hook.t
