name: Tk on Windows
run-name: Tk on Windows (branch ${{ inputs.perl-tk-branch }})

on:
  workflow_dispatch:
    inputs:
      perl-tk-branch:
        type: string
        default: master

jobs:
  test-tk-on-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - strawberry_version: 5.32.1.1
          - strawberry_version: 5.38.2.2
    steps:
      - uses: actions/checkout@v4
        with:
          repository: eserte/perl-tk
          ref: ${{ inputs.perl-tk-branch }}

#      - name: Remove pre-installed StrawberryPerl
#        run: |
#          Remove-Item -Path "C:\Strawberry" -Recurse -Force -ErrorAction SilentlyContinue

      - name: Install StrawberryPerl ${{ matrix.strawberry_version }}
        run: |
          if ("${{ matrix.strawberry_version }}" -eq "default") {
            choco install strawberryperl
          }
          elseif ("${{ matrix.strawberry_version }}" -ne "default") {
            choco install strawberryperl --version ${{ matrix.strawberry_version }} --force --allow-downgrade --install-arguments="'/l*v c:\StrawberryPerl_msi_install.log'"
          }

      - name: Display installation log
        if: failure()
        run: |
          type c:\StrawberryPerl_msi_install.log

      - name: Build and test
        run: |
          perl Makefile.PL
          gmake -j4 all
          gmake test
