name: Tk on Windows

on:
  workflow_dispatch:

jobs:
  test-tk-on-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - strawberry_version: 5.32.1.1
          - strawberry_version: default
    steps:
      - uses: actions/checkout@v4
        with:
          repository: eserte/perl-tk
      - name: Install StrawberryPerl ${{ matrix.strawberry_version }}
        run: |
          if ("${{ matrix.strawberry_version }}" -eq "default") {
            choco install strawberryperl
          }
          elseif ("${{ matrix.strawberry_version }}" -ne "default") {
            choco install strawberryperl --version ${{ matrix.strawberry_version }}
          }
      - name: Build and test
        run: |
          perl Makefile.PL
          gmake -j4 all
          gmake test
