name: Limited BBBike tests on Windows

on:
  workflow_dispatch:

jobs:
  test-bbbike-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: eserte/bbbike
          ref: XXX-appveyor
      - run: |
          cd t && perl -w -I.. -I..\lib bbbikebuildutil.t
#          prove -v t\bbbikebuildutil.t
