name: Test windows signals

on:
  workflow_dispatch:
    inputs:
      signal:
        type: choice
        options:
          - KILL
          - INT
          - BREAK
          - TERM
        default: KILL

jobs:
  test-windows-signals:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          perl scripts\windows-signals.pl ${{ inputs.signal }}
